"""auth and tenant onboarding

Identity mapping, cooperatives (tenants), memberships, cooperative
registration/verification and append-only audit/security events.

Revision ID: 0001
Revises: 
Create Date: 2026-09-25
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED', 'APPROVED', 'REJECTED', 'SUSPENDED', name='CooperativeStatus'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keycloak_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keycloak_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperative_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED', 'APPROVED', 'REJECTED', 'SUSPENDED', name='CooperativeStatus'), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('requested_information', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cooperative_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_cooperative_applications_status_submitted', 'cooperative_applications', ['status', 'submitted_at'], unique=False)
    op.create_index('uq_cooperative_applications_open_per_applicant', 'cooperative_applications', ['applicant_user_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED')"))
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('COOPERATIVE_MANAGER', 'COLLECTOR', 'FARMER', name='MembershipRole'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'REVOKED', name='MembershipStatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cooperative_id', 'role', name='uq_memberships_user_coop_role')
    )
    op.create_index('ix_memberships_cooperative_status', 'memberships', ['cooperative_id', 'status'], unique=False)
    op.create_table('registration_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('PHONE', 'EMAIL', name='VerificationChannel'), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'LOCKED', 'CONSUMED', name='VerificationStatus'), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_registration_verifications_destination_created', 'registration_verifications', ['destination', 'created_at'], unique=False)
    op.create_index('ix_registration_verifications_ip_created', 'registration_verifications', ['ip_address', 'created_at'], unique=False)
    op.create_index('ix_registration_verifications_user_created', 'registration_verifications', ['user_id', 'created_at'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('cooperative_id', sa.Uuid(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Audit and security events are append-only (docs: SECURITY.md). Enforce
    # it in the database so no application bug or endpoint can rewrite history.
    op.execute(
        """
        CREATE FUNCTION forbid_append_only_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
        END;
        $$
        """
    )
    for table in ("audit_events", "security_events"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_append_only_mutation()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_events')
    op.drop_index('ix_registration_verifications_user_created', table_name='registration_verifications')
    op.drop_index('ix_registration_verifications_ip_created', table_name='registration_verifications')
    op.drop_index('ix_registration_verifications_destination_created', table_name='registration_verifications')
    op.drop_table('registration_verifications')
    op.drop_index('ix_memberships_cooperative_status', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('uq_cooperative_applications_open_per_applicant', table_name='cooperative_applications', postgresql_where=sa.text("status IN ('PENDING', 'UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED')"))
    op.drop_index('ix_cooperative_applications_status_submitted', table_name='cooperative_applications')
    op.drop_table('cooperative_applications')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS forbid_append_only_mutation()")
    for enum_name in (
        "VerificationStatus",
        "VerificationChannel",
        "MembershipStatus",
        "MembershipRole",
        "CooperativeStatus",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
