"""Offline-first synchronisation: devices, their offline sessions, received mutations and the change log.

  devices          one row per installed MilkOS app (a random id generated on the device, never a fingerprint)
  device_sessions  the offline session of one user on one device (hashed secret, expiry, revocation)
  sync_mutations   every change a device pushed, keyed by (device, mutation_id) so a resend is never applied twice
  sync_changes     append-only change log; its id is the monotonically increasing server cursor clients pull from
"""
import datetime
import uuid

from sqlalchemy import (
    BigInteger, Boolean, Column, DateTime, ForeignKey, Index, Integer, String, Text, UniqueConstraint, Uuid, true,
)

from db import Base


class Device(Base):
    __tablename__ = "devices"

    id = Column(Uuid, primary_key=True, default=uuid.uuid4)
    # Random UUID generated by the app on first start and kept in its local database.
    device_identifier = Column(String(64), nullable=False, unique=True)
    # The cooperative this device works for. Set by the first cooperative user who registers it; a device
    # bound to one cooperative can't be used to sync for another (platform staff can release it).
    cooperative_id = Column(Uuid, ForeignKey("cooperatives.id", ondelete="CASCADE"), nullable=True, index=True)
    registered_by = Column(Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    label = Column(String(100))
    platform = Column(String(100))
    app_version = Column(String(50))
    user_agent = Column(String(500))
    is_active = Column(Boolean, nullable=False, default=True, server_default=true())
    last_seen_at = Column(DateTime)
    last_sync_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class DeviceSession(Base):
    """A user's offline session on one device. Only a SHA-256 hash of the secret is stored."""
    __tablename__ = "device_sessions"
    __table_args__ = (UniqueConstraint("device_id", "user_id", name="uq_device_sessions_device_user"),)

    id = Column(Uuid, primary_key=True, default=uuid.uuid4)
    device_id = Column(Uuid, ForeignKey("devices.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(Uuid, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    token_hash = Column(String(64), nullable=False, unique=True)
    # The secret replaced by the last rotation stays valid briefly, so a lost response doesn't lock the device out.
    previous_token_hash = Column(String(64), nullable=True, index=True)
    previous_valid_until = Column(DateTime, nullable=True)
    issued_at = Column(DateTime, default=datetime.datetime.utcnow)
    expires_at = Column(DateTime, nullable=False)
    last_validated_at = Column(DateTime)
    revoked_at = Column(DateTime)


class MutationStatus:
    APPLIED = "APPLIED"
    REJECTED = "REJECTED"   # validation / permission: retrying the same mutation won't help
    CONFLICT = "CONFLICT"   # needs a person to decide


class SyncMutation(Base):
    __tablename__ = "sync_mutations"
    __table_args__ = (
        UniqueConstraint("device_id", "mutation_id", name="uq_sync_mutations_device_mutation"),
        Index("ix_sync_mutations_coop_received", "cooperative_id", "received_at"),
        Index("ix_sync_mutations_device_local", "device_id", "local_id"),
    )

    id = Column(Uuid, primary_key=True, default=uuid.uuid4)
    device_id = Column(Uuid, ForeignKey("devices.id", ondelete="CASCADE"), nullable=False)
    mutation_id = Column(Uuid, nullable=False)
    user_id = Column(Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    cooperative_id = Column(Uuid, ForeignKey("cooperatives.id", ondelete="CASCADE"), nullable=True)
    entity_type = Column(String(40), nullable=False)
    operation = Column(String(20), nullable=False)
    local_id = Column(String(64), nullable=False)
    server_id = Column(String(64))
    status = Column(String(20), nullable=False)
    error_code = Column(String(50))
    error_message = Column(Text)
    client_timestamp = Column(DateTime)
    received_at = Column(DateTime, default=datetime.datetime.utcnow)
    resolved_at = Column(DateTime)
    resolution = Column(String(30))


class SyncChange(Base):
    """One row per change to a synchronised entity, written in the same transaction as the change.

    `id` is the pull cursor. Rows are appended by services/sync/tracking.py for every ORM write, so
    changes made online (cooperative workspace, superadmin) reach offline devices too.
    """
    __tablename__ = "sync_changes"
    __table_args__ = (Index("ix_sync_changes_coop_id", "cooperative_id", "id"),)

    id = Column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True, autoincrement=True)
    cooperative_id = Column(Uuid, ForeignKey("cooperatives.id", ondelete="CASCADE"), nullable=True)
    entity_type = Column(String(40), nullable=False)
    entity_id = Column(String(64), nullable=False)
    changed_at = Column(DateTime, nullable=False, default=datetime.datetime.utcnow)
